import Navbar from '@/Components/navigationBar'
import Head from 'next/head';
import React from 'react'

export default function ProjectsPage() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 bg-white dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="flex justify-between pt-10 mb-12 dark:text-white">
            <Navbar/>
          </nav>

          <div className="basis-2/3">
            <div className="text-start">
              <h2 className="pb-1 text-4xl font-medium text-teal-600 dark:text-teal-400 md:text-6xl">
                Projects
              </h2>
              <h3 className="text-2xl dark:text-white md:text-3xl">
                Software Engineer.
              </h3>
              <p className="max-w-xl leading-8 text-gray-800 text-md dark:text-gray-200 md:text-xl">
                I am an enthusiastic undergraduate who loves to solve problems
                with an engineering approach. I can quickly adapt to new
                technologies and use my full potential and skills to reach a
                successful outcome. I am interested in software development
                (full stack) and database design.
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
