"use client";
import Navbar from '@/components/navigationBar'
import Head from 'next/head';
import React from 'react'
import { useGlobalState } from '../context/GlobalStateContext';

export default function ProjectsPage() {
  const { number, setNumber, dark, setDark } = useGlobalState();
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`px-10 bg-white  md:px-20 lg:px-40 ${dark?"bg-gray-900 ":"bg-white"}`}>
        <section className="min-h-screen">
        <nav className={`flex justify-between pt-10 mb-12  ${dark?"text-white":"text-gray-900"}`}>
            <Navbar />
          </nav>

          <div className="basis-2/3">
            <div className="text-start">
              <h2 className="pb-1 text-4xl font-medium text-teal-600 dark:text-teal-400 md:text-6xl">
                Projects
              </h2>
              <h3 className="text-2xl dark:text-white md:text-3xl">
                Software Engineer.
              </h3>
              <ul className={`list-disc pl-5 ${dark ? "text-white" : "text-gray-700"}`}>
                <li>
                  <strong>Vis-BRIDGE</strong> (2021): This device can control the electrical equipment based on the hand gestures given by the user. The project was developed based on the Raspberry Pi single board computer. Computer vision algorithms were employed to identify the hand gestures. A power electronic circuit controlled the power delivered to the equipment.
                </li>
                <li>
                  <strong>RISC-V Processor</strong> (2023): We designed a single cycle 32-bit RISC-V processor as per the RV32I ISA specification. It also consisted of a cache memory with victim cache functionality. The processor was optimized for its performance and resource usage.
                </li>
                <li>
                  <strong>AquaMate</strong> (2023): This project aims to develop a system to automate processes in commercial aquariums and fish farms, including water quality monitoring, anomaly detection, and automating the fish feeding process. A dashboard is provided for monitoring and commanding.
                </li>
                <li>
                  <strong>Voltage Regulator</strong> (2022): Developed a voltage regulator for high-power applications. The regulated voltage is 28 volts with a maximum current rating of 30 amperes. An overcurrent protection circuit was also added. Maintaining an acceptable ripple ratio and thermal management were crucial in this project.
                </li>
                <li>
                  <strong>High-Frequency Amplifier</strong> (2022): Our team designed a power amplifier for high-frequency operations. We achieved excellent test results with high gain and no significant waveform distortion. The power gain is around 20 decibels.
                </li>
                <li>
                  <strong>Autonomous Robot</strong> (2021): We developed an autonomous mobile robot simulation for the EN2532 - Robot Design and Competition Module. It included maze solving, object detection, and placing, among other features. Webots simulator was used as the simulation platform.
                </li>
              </ul>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
