"use client";
import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import Navbar from "@/Components/navigationBar";
import { TypeAnimation } from "react-type-animation";
import { useGlobalState } from "./context/GlobalStateContext";

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const { number, setNumber, dark, setDark } = useGlobalState();
  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    <div className={dark ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-10 bg-white dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="flex justify-between pt-10 mb-12 dark:text-white">
            <Navbar />
          </nav>
          <div className="lg:flex">
            <div className="basis-2/3">
              <div className="text-start">
                <h2 className="pb-1 text-4xl font-medium text-teal-600 dark:text-teal-400 md:text-6xl my-4">
                  Chinthana Prabhashitha
                </h2>
                <h3 className="text-lg dark:text-white md:text-2xl my-4">
                  <TypeAnimation
                    sequence={[
                      "Developer",
                      1000,
                      "Problem Solver",
                      1000,
                      "Designer",
                      1000,
                      "Software Engineer",
                      1000,
                    ]}
                    speed={50}
                    repeat={0}
                    style={{ fontSize: "2em" }}
                  />
                </h3>
                <p className="max-w-xl leading-8 text-gray-800 text-md dark:text-gray-200 md:text-xl text-justify">
                  I am an enthusiastic undergraduate with a passion for solving
                  complex problems using an engineering approach. My ability to
                  quickly adapt to new technologies allows me to leverage my
                  full potential and skills to achieve successful outcomes. I am
                  particularly interested in software development, with a focus
                  on full-stack development, and database design. My academic
                  background has equipped me with a strong foundation in both
                  theoretical and practical aspects of these areas, and I am
                  eager to apply my knowledge to real-world projects. I thrive
                  in dynamic environments where I can continuously learn and
                  grow, and I am committed to contributing to innovative
                  solutions in the field of software engineering.
                </p>
                <div className="flex justify-start gap-6 py-5 text-5xl text-gray-600 dark:text-gray-400">
                  <AiFillTwitterCircle size={40} />
                  <AiFillLinkedin size={40} />
                  <AiFillYoutube size={40} />
                  <AiFillGithub size={40} />
                </div>
                
              </div>
            </div>
            {mounted && (
              <motion.div
                initial={{ x: "100vw" }}
                animate={{ x: 0 }}
                transition={{ type: "spring", stiffness: 200, damping: 20 }}
                className="basis-1/3"
              >
                <img src="/Portrait.png" alt="Portrait" className="" />
              </motion.div>
            )}
          </div>
        </section>
      </main>
    </div>
  );
}
